const Employee =[
    {
        id:'1',
        uname:'MAX',
        age:'24',
        desg:'Developer',
        salary:20000
    },
    {
        id:'2',
        uname:'Riya',
        age:'22',
        desg:'Tester',
        salary:30000
    },
    {
        id:'3',
        uname:'Asish',
        age:'24',
        desg:'Developer',
        salary:25000
    },
    {
        id:'4',
        uname:'Sidharth',
        age:'22',
        desg:'Tester',
        salary:23000
    }
]
export default Employee;